name: "Checkov"
description: "Running Checkov in actions"
inputs:
  path:
    description: "Path to the code"
    required: false
    type: string
    default: ""
  planfilename:
    description: "name of the plan file"
    required: false
    type: string
    default: ""
  config:
    description: "Path co custom config"
    required: false
    type: string
    default: ""
  githubapi:
    required: true

outputs:
  checkov_results:
    description: "checkovresults"
    value: ${{ steps.checkov.outcome}}

runs:
  using: "composite"
  steps:
    - name: Custom Checks
      uses: actions/checkout@v4
      with:
        repository: ghostfacts/checkov
        ref: main
        path: checkov
        fetch-depth: 0
        sparse-checkout: |
          checkov_config.yml
          custom_policy

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Use any supported Python version
    
    - name: Install yq
      run: |
        python -m pip install yq
      shell: bash

    # - name: Merge Checkov Configs
    #   run: |
    #     yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' checkov/checkov_config.yml ${{ inputs.config }} > checkov/checkov_config.yml
    #   shell: bash

    - name: Scan code
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      env:
        GITHUB_OVERRIDE_URL: true
      with:
        config_file: /github/workspace/checkov/checkov_config.yml
        external_checks_dirs: /github/workspace/checkov/custom_policy/
        file: ${{ inputs.path }}/${{ inputs.planfilename }}
        repo_root_for_plan_enrichment: ${{ inputs.path }}
        output_file_path: console,results.sarif
        download_external_modules: true
        github_pat: ${{ inputs.githubapi }}
        quiet: true