name: "Checkov"
description: "Running Checkov in actions"
#inputs
#outputs
runs:
#  using: "composite"
  steps:
    - name: Custom Checks
      uses: actions/checkout@v4
      with:
        repository: ghostfacts/checkov
        ref: main
        path: checkov
        fetch-depth: 0
        sparse-checkout: |
          checkov.yml
          custom_policy
    - run: |
        ls -hal
    - name: Scan code
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      env:
        GITHUB_OVERRIDE_URL: true
      continue-on-error: true
      with:
        config_file: /github/workflow/checkov/checkov.yml
        external_checks_dirs: /github/workflow/checkov/custom_policy/
        skip_check: testck
        output_file_path: console,results.sarif
        download_external_modules: true
        github_pat: ${{ secrets.token }}
        quiet: true
      

