name: "Checkov"
description: "Running Checkov in actions"
inputs:
  config:
    description: "Path co custom config"
    required: false
    type: string
    default: ""
  githubapi:
    required: true

outputs:
  checkov_results:
    description: "checkovresults"
    value: ${{ steps.checkov.outcome}}

runs:
  using: "composite"
  steps:
    - name: Custom Checks
      uses: actions/checkout@v4
      with:
        repository: ghostfacts/checkov
        ref: main
        path: checkov
        fetch-depth: 0
        sparse-checkout: |
          checkov_config.yml
          custom_policy

    - name: Merge Checkov Configs
      run: |
        sudo add-apt-repository ppa:rmescandon/yq; sudo apt update; sudo apt install yq -y
        if [ -s ".checkov.yaml" ]; then
            echo "Found File .checkov.yaml"
            yq eval-all '. as $item ireduce ({}; . *+ $item)' checkov/checkov_config.yml .checkov.yaml --inplace
        fi
        if [ -s ".checkov.yml" ]; then
            echo "Found File .checkov.yml"
            yq eval-all '. as $item ireduce ({}; . *+ $item)' checkov/checkov_config.yml .checkov.yml --inplace
        fi

        if [ -s ${{inputs.config}} ]; then
            yq eval-all '. as $item ireduce ({}; . *+ $item)' checkov/checkov_config.yml ${{inputs.config}} --inplace
        fi
      shell: bash

    - name: Scan code
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      env:
        GITHUB_OVERRIDE_URL: true
      continue-on-error: true
      with:
        config_file: /github/workspace/checkov/checkov_config.yml
        external_checks_dirs: /github/workspace/checkov/custom_policy/
        output_file_path: console,results.sarif
        download_external_modules: true
        github_pat: ${{ inputs.githubapi }}
        quiet: true
#send results over
    - name: Checkov Failed
      if: steps.checkov.outcome == 'failure'
      run: |
        echo "Checkov found some issues"
        exit 1
      shell: bash      
