name: "Checkov"
description: "Running Checkov in actions"
#inputs
#outputs
runs:
  using: "composite"
  steps:
    - name: Custom Checks
      uses: actions/checkout@v4
      with:
        repository: ghostfacts/checkov
        ref: main
        path: checkov
        fetch-depth: 0
        sparse-checkout: |
          checkov.yml
          custom_policy

