name: "Checkov"
description: "Running Checkov in actions"
#inputs
#outputs
runs:
  using: "composite"
  steps:
    - name: Custom Checks
      uses: actions/checkout@v4
      with:
        repository: ghostfacts/checkov
        ref: main
        path: checkov
        fetch-depth: 0
        sparse-checkout: |
          checkov_config.yml
          custom_policy

    - name: merge configs
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y
        ls -hal
        if [ -s ".checkov.yaml" ]; then
            yq eval-all '. as $item ireduce ({}; . *+ $item)' checkov/checkov_config.yaml .checkov.yaml --inplace
        fi
      shell: bash

    - name: Scan code
      id: checkov
      uses: bridgecrewio/checkov-action@v12
      env:
        GITHUB_OVERRIDE_URL: true
      continue-on-error: true
      with:
        config_file: /github/workspace/checkov/checkov_config.yml
        external_checks_dirs: /github/workspace/checkov/custom_policy/
        # skip_check: testck
        output_file_path: console,results.sarif
        download_external_modules: true
        # github_pat: ${{ secrets.token }}
        quiet: true
      

